## **5. Pipeline de Integração Contínua (`.github/workflows/ci-pipeline.yml`)**

```yaml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt

      - name: Executar Testes
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Construir Imagem Docker
        run: docker build -t flask-app .
```
